swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /signup:
    get:
      operationId: "signup.send"
      # tags:
        # - "SignUp"
      # summary: "The people sign up data"
      # description: "Read the list of people"

      responses:
        200:
          description: "OK"
          examples:
            application/json:
             {
               "status": "Success"
             }
  /camera1:
    get:
      operationId: "image.showim1"
      responses:
        200:
          description: "OK"
  /camera2:
    get:
      operationId: "image.showim2"
      responses:
        200:
          description: "OK"
  /image_encoded1:
    get:
      operationId: "image.encode_im1"
      responses:
        200:
          description: "OK"
  /image_encoded2:
    get:
      operationId: "image.encode_im2"
      responses:
        200:
          description: "OK"
  /info:
    get:
      operationId: "stats.main"
      responses:
        200:
          description: "OK"
  /kml:
    get:
      operationId: "show_kml.download"
      responses:
        200:
          description: "OK"
