swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /signup:
    get:
      operationId: "signup.send"
      # tags:
        # - "SignUp"
      # summary: "The people sign up data"
      # description: "Read the list of people"

      responses:
        200:
          description: "OK"
          examples:
            application/json:
             {
               "status": "Success"
             }
  /image:
    get:
      operationId: "image.showim"
      responses:
        200:
          description: "OK"
  /image_encoded:
    get:
      operationId: "image.encode_im"
      responses:
        200:
          description: "OK"
<<<<<<< HEAD:Backend/Api/swagger.yml
  /info:
    get:
      operationId: "stats.main"
      responses:
        200:
          description: "OK"
  /kml:
    get:
      operationId: "show_kml.download"
      responses:
        200:
          description: "OK"
=======
>>>>>>> d73b2f589494e9326c96ce8f3798a31c4d95098a:Backend/docker_api/swagger.yml
