swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /signup:
    get:
      operationId: "signup.send"
      # tags:
        # - "SignUp"
      # summary: "The people sign up data"
      # description: "Read the list of people"

      responses:
        200:
          description: "OK"
          examples:
            application/json:
             {
               "status": "Success"
             }
  /camera1:
    get:
      operationId: "image.showim_main1"
      responses:
        200:
          description: "OK"

  /camera2:
    get:
      operationId: "image.showim_main2"
      responses:
        200:
          description: "OK"

  /camera_mag1:
    get:
      operationId: "image.showim_mag1"
      responses:
        200:
          description: "OK"

  /camera_mag2:
    get:
      operationId: "image.showim_mag2"
      responses:
        200:
          description: "OK"
  /info1:
    get:
      operationId: "stats.main1"
      responses:
        200:
          description: "OK"
  /info2:
    get:
      operationId: "stats.main2"
      responses:
        200:
          description: "OK"
  /orbit_main:
    get:
      operationId: "show_kml.send_main_file_orbit1"
      responses:
        200:
          description: "OK"
  /orbit_mag:
    get:
      operationId: "show_kml.send_main_file_orbit2"
      responses:
        200:
          description: "OK"


